function [varargout] = LammpsStrDeleteCell(varargin)
%% Description
%
% *Command*:
% data_cell = LammpsDeleteAtom(data_cell,data_cell_selected)
%
% *Input*:
% data                  :   structure that generated by function LammpsStrCellCoord.
% data_cell_selected    :   structure that generated by function LammpsStrSelectCell
%% Reading Input

data_cell            =   varargin{1};
data_cell_selected   =   varargin{2};

%% Deleting Cells

data_cell.coord_cell(data_cell_selected.cell_selected,:)   =   [];
data_cell.num_cells  =   data_cell.num_cells - data_cell_selected.num_cell_selected;

%% ---------------------Output-----------------------------

varargout{1}        =   data_cell;