function [varargout] = LammpsStrDeleteAtom(varargin)
%% Description
%
% *Command*:
% data = LammpsDeleteAtom(data,data_atom_selected)
%
% *Input*:
% data          :   structure that generated by function LammpsStrGenerate.
% data_atom_selected :   structure that generated by function LammpsStrSelectAtom.

%% Reading Input

data                =   varargin{1};
data_atom_selected  =   varargin{2};

%% Deleting Atoms

data.data_atom(data_atom_selected.atom_selected,:)   =   [];
data.num_atoms  =   data.num_atoms - data_atom_selected.num_atom_selected;

%% Deleting Bonds

try 
    data.data_bond;
    flag_bond = 1;
catch
    flag_bond = 0;
end

if flag_bond == 1
    data.data_bond(data_atom_selected.bond_selected,:)   =   [];
    data.num_bonds  =   data.num_bonds - data_atom_selected.num_bond_selected;
    data.data_bond(:,1) = 1 : data.num_bonds;
end

%% Deleting Angles

try 
    data.data_angle;
    flag_angle = 1;
catch
    flag_angle = 0;
end

if flag_angle == 1
    data.data_angle(data_atom_selected.angle_selected,:)   =   [];
    data.num_angles  =   data.num_angles - data_atom_selected.num_angle_selected;
    data.data_angle(:,1) = 1 : data.data_angle;
end


%% ---------------------Output-----------------------------

varargout{1}        =   data;